config/routes.rb
Rails.application.routes.draw do
  root to: 'divisions#index'
  resources :projects do
    resources :employees
  end
  
  resources :divisions do
    resources :employees
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/division.rb
class Division < ApplicationRecord
  has_many :employees
  validates :name, presence: true
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :division
  has_many :employee_projects
  has_many :projects, :through => :employee_projects


end

app/models/employee_project.rb
class EmployeeProject < ApplicationRecord
  belongs_to :employee
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :employee_projects
  has_many :employees, :through => :employee_projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  def index
    @divisions = Division.all
    render :index
  end

  def new
    @division = Division.new
    render :new
  end

  def create
    @division = Division.create(division_params)
    if @division.save
      redirect_to divisions_path
    else
      render :new
    end
  end

  def show
    @division = Division.find(params[:id])
    render :show
  end

  def edit
    @division = Division.find(params[:id])
    render :edit
  end

  def update
    @division= Division.find(params[:id])
      if @division.update(division_params)
        redirect_to divisions_path
      else
        render :edit
      end
  end

  def destroy
    @division = Division.find(params[:id])
    @division.destroy
    redirect_to divisions_path
  end

  private
  def division_params
    params.require(:division).permit(:name)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def new
    @division = Division.find(params[:division_id])
    @employee = @division.employees.new
    render :new
  end

  def create
    @division = Division.find(params[:division_id])
    @employee = @division.employees.new(employee_params)
    if @employee.save
      redirect_to division_path(@division)
    else
      render :new
    end
  end

  def edit
    @employee = Employee.find(params[:id])
    :edit
  end

  def show
    @division = Division.find(params[:division_id])
    @employee = Employee.find(params[:id])
    @projects = @employee.projects.distinct
    render :show
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to division_path(@employee.division)
  end

  def update
    @project = Project.find(params[:project_id])
    @employee = Employee.find(params[:id])
    @employee.projects.push(@project)
    @employee.save
    redirect_to division_employee_path(division_id: @employee.division_id, id: @employee.id, project_title: @project.title)
  end

  private
    def employee_params
      params.require(:employee).permit(:name)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
 def index
   @projects = Project.all
   render :index
 end

 def new
   @project = Project.new
   render :new
 end

 def create
   @project = Project.new(project_params)
   if @project.save
     redirect_to projects_path
   else
     render :new
   end
 end

 def show
   @project = Project.find(params[:id])
   @available_employees = Employee.all
   @assigned_employees = @project.employees.distinct
   :show
 end

 def edit
   @project = Project.find(params[:id])
   :edit
 end

 def destroy
   @project = Project.find(params[:id])
   @project.destroy
   redirect_to projects_path
 end

 def update
   @project = Project.find(params[:id])
   @employee = Employee.find(params[:employee_id])
   @project.employees.delete(@employee)
   redirect_to projects_path
 end


 private
 def project_params
   params.require(:project).permit(:title)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/divisions/edit.html.erb
<h1>Edit Divisions</h1>

<%= render "layouts/division_form" %>

<p><%= link_to "Delete division", division_path(@division), :data => {:confirm => "Delete #{@division.name}?", :method => "delete"} %> </p>

<% content_for(:nav) do %>
  <p><%= link_to "Divisions", divisions_path %></p>
  <p><%= link_to "Back to #{@division.name}", division_path(@division) %></p>
<% end %>

app/views/divisions/index.html.erb
<h1>Divisions:</h1>

<% if @divisions.any? %>
  <ul>
    <% @divisions.each do |division| %>
      <li><%= link_to division.name, division_path(division) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no divisions yet.</p>
<% end %>

<p><%= link_to "Add a division", new_division_path %></p>

<p><%= link_to "Projects", projects_path %></p>

app/views/divisions/new.html.erb
<h1>New division</h1>

<%= render "layouts/division_form" %>

app/views/divisions/show.html.erb
<h1><%= @division.name %></h1>

<p><%= link_to "Edit division", edit_division_path %></p>

<h2>Employees:</h2>

<% if @division.employees.any? %>
  <h4>Here are the employees for this division:</h4>

  <% @division.employees.each do |employee| %>
    <ul>
      <li>
        <%= link_to employee.name, division_employee_path(@division, employee.id) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No employees are listed for this division.</p>
<% end %>

<p><%= link_to "Add an employee", new_division_employee_path(@division) %></p>

<% content_for(:nav) do %>
  <p><%= link_to "Divisions", divisions_path %></p>
<% end %>

app/views/employees/edit.html.erb
<h1>Edit employee</h1>

<%= render "layouts/employee_form" %>

<p><%= link_to "Delete employee", employee_path(@employee), :data => {:confirm => "Delete #{@employee.title}?", :method => "delete"} %> </p>

<% content_for(:nav) do %>
  <p><%= link_to "employees", employees_path %></p>
  <p><%= link_to "Back to #{@employee.title}", employee_path(@employee) %></p>
<% end %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render "layouts/employee_form" %>

<% content_for(:nav) do %>
<p><%= link_to "Divisions", divisions_path %></p>
 <% end %>

app/views/employees/show.html.erb
<h1>Name: <%= @employee.name %></h1>
<h2>Division: <%= @division.name %></h2>
<h2>Current Projects:</h2>

<% if @projects.any? %>
<ul>
  <% @projects.each do |project| %>
    <li><%= link_to project.title, project_path(project.id) %></li>
    <% end %>
    </ul>
    <% else %>
    <p>No projects assigned</p>
    <% end %>
<p><%= link_to "Edit employee", edit_division_employee_path(@division, @employee) %></p>
<p><%= link_to "Fire employee", division_employee_path(@division, @employee),
                        :data => {:confirm => "Release the hounds?",
                                       :method => "delete"} %></p>

<% content_for(:nav) do %>
<p><%= link_to "Divisions", divisions_path %></p>
 <% end %>

app/views/layouts/_division_form.html.erb
<%= render "layouts/errors", :object => @division %>

<%= form_for @division do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/layouts/_employee_form.html.erb
<%= render "layouts/errors", :object => @employee %>

<%= form_for [@division, @employee] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_project_form.html.erb
<%= render "layouts/errors", :object => @project %>

<%= form_for @project do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <%= yield :nav %>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render "layouts/project_form" %>

<p><%= link_to "Delete project", project_path(@project), :data => {:confirm => "Delete #{@project.title}?", :method => "delete"} %> </p>

<% content_for(:nav) do %>
  <p><%= link_to "Projects", projects_path %></p>
  <p><%= link_to "Back to #{@project.title}", project_path(@project) %></p>
<% end %>

app/views/projects/index.html.erb
<h1>Projects:</h1>

<% if @projects.any? %>
  <ul>
    <% @projects.each do |project| %>
      <li><%= link_to project.title, project_path(project) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no projects yet.</p>
<% end %>

<p><%= link_to "Add a project", new_project_path %></p>

<p><%= link_to "Divisions", divisions_path %></p>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "layouts/project_form" %>

<% content_for(:nav) do %>
  <p><%= link_to "Projects", projects_path %></p>
<% end %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<p><%= link_to "Edit project", edit_project_path %></p>

<h2>Assigned Employees:</h2>
<% if @assigned_employees.any? %>
  <% @assigned_employees.each do |employee| %>
    <ul>
      <li>
        <p><%= link_to employee.name, division_employee_path(employee.division_id, employee.id) %></p>
        <p><%= link_to "Unassign", project_path(@project, employee_id: employee.id), :data => {:method => "patch"}%></p
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No employees assigned </p>
<% end %>

<h2>Avilable Employees:</h2>

<% if @available_employees.any? %>
  <% @available_employees.each do |employee| %>
    <ul>
      <li>
        <p><%= link_to employee.name, division_employee_path(employee.division_id, employee.id) %></p>
        <p><%= link_to "Assign to Project", project_employee_path(@project, employee.id), :data => {:method => "patch"}%></p>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No employees are listed </p>
<% end %>

<% content_for(:nav) do %>
  <p><%= link_to "Projects", projects_path %></p>
<% end %>